### ISSUE TITLE
CRAN checklist

### ISSUE THREAD

**Issue by graysonwhite** [USDAForestService/FIESTAutils#1]
Tasks to complete before submitting to CRAN:

- [x] Remove `arcgisbinding` package as Suggests and functions that use the package. 
    - `DBtestESRIgdb()`: needs to go
    - datExportdata.R: line 129
    - `write2gdb()`: needs to go
    - pcheck.functions.R: `pcheck.output()` lines 597, 598, 600
    - Suggests field of DESCRIPTION
- [x] Change `.Call()` calls in Chris' C++ code (hopefully we can use `rgdal::GDALcall`)
- [x] Update Title and Description field and DESCRIPTION file. 
- [x] Deal with potential global variable issues. The remaining issues are in `raster_analysis.R`, just a couple global variable definitions we need to deal with.

**Comment by graysonwhite** [comment]
**Review tasks from CRAN (to-do before resubmission):** 
- [x] If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

- [x] Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      checks_desc.Rd: \value
      DBtestPostgreSQL.Rd: \value
      DBtestSQLite.Rd: \value
      estimation_desc.Rd: \value
      internal_desc.Rd: \value
      pcheck_desc.Rd: \value
      raster_desc.Rd: \value
      spatial_desc.Rd: \value
      write2_desc.Rd: \value

- [x] You write information messages to the console that cannot be easily
suppressed. It is more R like to generate objects that can be used to
extract the information a user is interested in, and then print() that
object. Instead of print()/cat() rather use message()/warning() or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console. (except for print, summary, interactive functions)

- [x] Please make sure that you do not change the user's options, par or
working directory. If you really have to do so within functions, please
ensure with an *immediate* call of on.exit() that the settings are reset
when the function is exited. e.g.:
...
oldpar <- par(no.readonly = TRUE)    # code line i
on.exit(par(oldpar))            # code line i + 1
...
par(mfrow=c(2,2))            # somewhere after
...
e.g.: R/SAest.pbar.R

- [x]  You are using installed.packages() in your code. As mentioned in the
notes of installed.packages() help page, this can be very slow.
Therefore please do not use installed.packages().

**Comment by graysonwhite** [comment]
`FIESTAutils` v1.0.0 was accepted to CRAN 2/28/2022.
